import useStore from './Store';

export const useGetStyles = () => {
  const { mode } = useStore();

  const styles = {
    headerStyle: {
      backgroundColor: mode === 'dark' ? '#212529' : '#f8f9fa',
      elevation: 0,
      shadowOpacity: 0,
      borderBottomWidth: 0,
      height: 40,
      paddingVertical: 0,
      borderRadius: 15,
    },
    headerTintColor: mode === 'dark' ? '#fff' : '#212529',
    headerTitleStyle: {
      fontWeight: 'bold',
      fontSize: 18,
    },
    headerTitleAlign: 'center',
    container: {
      flex: 1,
      padding: 20,
      backgroundColor: mode === 'dark' ? '#212529' : '#fff',
      borderRadius: 10,
      justifyContent: 'center',
      alignItems: 'center',
    },
    menuItem: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 15,
      marginVertical: 10,
      backgroundColor: '#005eb8',
      width: '80%',
      borderRadius: 5,
    },
    menuIcon: {
      marginRight: 10,
    },
    menuText: {
      color: '#fff',
      fontSize: 18,
      fontWeight: 'bold',
      textAlign: 'center',
    },
    title: {
      fontSize: 24,
      fontWeight: 'bold',
      marginBottom: 20,
      color: mode === 'dark' ? '#fff' : '#212529',
    },
    radioContainer: {
      width: '100%',
    },
    radioItem: {
      flexDirection: 'row',
      alignItems: 'center',
      marginVertical: 10,
    },
    radioText: {
      fontSize: 18,
      color: mode === 'dark' ? '#fff' : '#212529',
    },
    cartItem: {
      flex: 1,
      padding: 10,
      backgroundColor: mode === 'dark' ? '#fff' : '#212529',
      borderRadius: 10,
    },
    cartItemImage: {
      width: 100,
      height: 100,
      borderRadius: 10,
    },
    cartItemDetail: {
      flex: 1,
      padding: 10,
      backgroundColor: mode === 'dark' ? '#fff' : '#212529',
      borderRadius: 10,
    },
    cartSummary: {
      flex: 1,
      padding: 10,
      backgroundColor: mode === 'dark' ? '#fff' : '#212529',
      borderRadius: 10,
    },
    button: {
      padding: 10,
      margin: 5,
      backgroundColor: '#005eb8',
      borderRadius: 10,
    },
    redButton: {
      padding: 10,
      margin: 5,
      backgroundColor: '#ff0000',
      borderRadius: 10,
    },
    input: {
      padding: 10,
      margin: 5,
      borderColor: mode === 'dark' ? '#005eb8' : '#212529',
      borderWidth: 1,
      backgroundColor: mode === 'dark' ? '#212529' : '#fff',
      color: mode === 'dark' ? '#fff' : '#212529',
      borderRadius: 10,
      fontSize: 16,
      fontWeight: '500',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 1.5,
      elevation: 2,
      placeholderTextColor: mode === 'dark' ? '#ccc' : '#212529',
    },
    label: {
      fontSize: 16,
      fontWeight: 'bold',
      color: mode === 'dark' ? '#212529' : '#fff',
    },
    activityIndicator: {
      margin: 5,
    },
    error: {
      color: 'red',
      fontSize: 16,
      textAlign: 'center',
    },
    category: {
      padding: 10,
      margin: 5,
      backgroundColor: mode === 'dark' ? '#fff' : '#212529',
      borderRadius: 10,
    },
    filterItem: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      padding: 10,
      margin: 5,
      backgroundColor: mode === 'dark' ? '#212529' : '#fff',
      borderRadius: 10,
      borderWidth: 1,
    },
    filterText: {
      flex: 1,
      marginLeft: 5,
      color: mode === 'dark' ? '#fff' : '#212529',
      fontSize: 16,
    },
    material: {
      padding: 10,
      margin: 5,
      backgroundColor: mode === 'dark' ? '#fff' : '#212529',
      borderRadius: 10,
    },
    productItem: {
      padding: 10,
      margin: 5,
      backgroundColor: mode === 'dark' ? '#fff' : '#212529',
      borderRadius: 10,
    },
    noResults: {
      fontSize: 16,
      fontWeight: 'bold',
      color: mode === 'dark' ? '#212529' : '#fff',
    },
    enhancedContainer: {
      flex: 1,
      padding: 16,
      backgroundColor: mode === 'dark' ? '#fff' : '#212529',
      borderRadius: 10,
    },
    filterContainer: {
      flex: 1,
      padding: 16,
      backgroundColor: mode === 'dark' ? '#212529' : '#fff',
      borderRadius: 10,
    },
    card: {
      borderWidth: 1,
      borderColor: '#005eb8',
      borderRadius: 10,
      overflow: 'hidden',
      margin: 10,
      backgroundColor: mode === 'dark' ? '#212529' : '#fff',
    },
    cardTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: mode === 'dark' ? '#fff' : '#212529',
    },
    cardText: {
      fontSize: 16,
      color: mode === 'dark' ? '#fff' : '#212529',
    },
    buttonText: {
      color: '#fff',
      textAlign: 'center',
    },
    productImage: {
      width: '100%',
      height: '100%',
      resizeMode: 'cover',
      margin: 0,
      padding: 0,
      borderRadius: 10,
    },
    cardBody: {
      padding: 10,
    },
    buttonDisabled: {
      backgroundColor: '#aaa',
      padding: 10,
      marginTop: 10,
      borderRadius: 10,
    },
    image: {
      width: '100%',
      height: 200,
      resizeMode: 'cover',
    },
    grayscaleImage: {
      width: '100%',
      height: 200,
      resizeMode: 'cover',
      tintColor: 'gray',
    },
    categoryImage: {
      width: '100%',
      height: 200,
      resizeMode: 'cover',
    },
    text: {
      color: mode === 'dark' ? '#fff' : '#212529',
      fontSize: 16,
    },
    priceText: {
      color: mode === 'dark' ? '#fff' : '#212529',
      fontSize: 18,
      fontWeight: 'bold',
    },
    outOfStockButton: {
      backgroundColor: '#aaa',
      padding: 10,
      borderRadius: 10,
    },
    addToCartButton: {
      backgroundColor: '#005eb8',
      padding: 10,
      borderRadius: 10,
    },
    imageContainer: {
      position: 'relative',
      width: '100%',
      height: 200,
    },
    imageTitle: {
      position: 'absolute',
      width: '100%',
      textAlign: 'center',
      top: '50%',
      transform: [{ translateY: -20 }],
      fontSize: 40,
      fontWeight: 'bold',
      color: '#fff',
      shadowColor: 'black',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.5,
      shadowRadius: 10,
    },
    pagination: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
    },
    pageItem: {
      margin: 5,
    },
    pageText: {
      fontSize: 16,
      color: '#005eb8',
    },
    toggleButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 10,
      marginTop: 10,
      backgroundColor: '#005eb8',
      borderRadius: 10,
    },
    toggleLabel: {
      fontSize: 18,
      marginRight: 10,
      color: 'white',
    },
    bold: {
      fontWeight: 'bold',
    },
    item: {
      padding: 10,
      marginVertical: 5,
      backgroundColor: mode === 'dark' ? '#444' : '#ddd',
      borderRadius: 10,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    summary: {
      padding: 20,
      margin: 10,
      backgroundColor: mode === 'dark' ? '#212529' : '#fff',
      borderRadius: 10,
      shadowColor: '#212529',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 1.5,
      elevation: 3,
    },
    summaryTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: mode === 'dark' ? '#fff' : '#212529',
      marginBottom: 10,
    },
    cartContainer: {
      flex: 1,
      padding: 0,
      alignItems: 'stretch',
    },
    cartHeader: {
      fontSize: 24,
      fontWeight: 'bold',
      color: mode === 'dark' ? '#fff' : '#212529',
    },
    cartListItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 10,
      borderBottomWidth: 1,
      borderBottomColor: '#cccccc',
    },
    cartImage: {
      width: 50,
      height: 50,
    },
    table: {
      width: '100%',
      alignItems: 'stretch',
    },
    tableRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      padding: 10,
      borderBottomWidth: 1,
      borderBottomColor: '#cccccc',
      alignItems: 'center',
    },
    tableCell: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 5,
      borderWidth: 1,
      borderColor: '#cccccc',
      borderStyle: 'solid',
    },
    quantityControls: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    icon: {
      color: mode === 'dark' ? '#fff' : '#212529',
    },
    cartText: {
      color: mode === 'dark' ? '#fff' : '#212529',
    },
    scrollView: {
      width: '100%',
    },
    dataTable: {
      width: '100%',
    },
    buttonContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      padding: 10,
    },
    filterSection: {
      flex: 1,
      marginHorizontal: 50,
      paddingVertical: 10,
    },
    list: {
      flexDirection: 'row',
      flexWrap: 'wrap',
    },
    tableHeaderText: {
      fontWeight: 'bold',
      fontSize: 16,
      color: mode === 'dark' ? '#fff' : '#212529',
      textAlign: 'center',
    },
    totalPriceContainer: {
      padding: 10,
      margin: 10,
      backgroundColor: mode === 'dark' ? '#212529' : '#fff',
      borderRadius: 10,
      alignItems: 'center',
    },
    totalPriceText: {
      fontSize: 18,
      fontWeight: 'bold',
      color: mode === 'dark' ? '#fff' : '#212529',
    },
  };

  return { styles, mode };
}
